descriptor-schema-version: "2.2"
info:
  name: GW Connection Service-0.8.7
  version: 0.8.7
app:
  cpuarch: x86_64
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    profile: custom
    cpu: 100
    memory: 100
    disk: 10
    network:
      -
        interface-name: eth0
        ports:
          tcp:
           - 8080
  startup:
    rootfs: rootfs.tar
    target:
    - ./gw_server
  type: docker
